### ISSUE TITLE
group by | empty column

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2020-e-qgis-points2one#17]
To reproduce:

1) check "Group by"
2) leave column empty
3) click OK

```
Traceback (most recent call last):
  File "/home/martin/git/ctu-fgis/2020-e-qgis-points2one/Point2One.py", line 368, in Point2One
    linestring_layer = self.createLinestringLayer(point_layer)
  File "/home/martin/git/ctu-fgis/2020-e-qgis-points2one/Point2One.py", line 280, in createLinestringLayer
    attrValue = feature.attribute(groupbyAttr)
KeyError: ''
```

**Comment by landam** [comment]
Similar issue with "Sort by"

```
Traceback (most recent call last):
  File "/home/martin/git/ctu-fgis/2020-e-qgis-points2one/Point2One.py", line 368, in Point2One
    linestring_layer = self.createLinestringLayer(point_layer)
  File "/home/martin/git/ctu-fgis/2020-e-qgis-points2one/Point2One.py", line 267, in createLinestringLayer
    features.sort(key=lambda a: a.attribute(sortAttr))
  File "/home/martin/git/ctu-fgis/2020-e-qgis-points2one/Point2One.py", line 267, in 
    features.sort(key=lambda a: a.attribute(sortAttr))
KeyError: ''
```
